-- AlterTable
ALTER TABLE "Bookout" ADD COLUMN     "authId" TEXT,
ADD COLUMN     "baseAverageTradeIn" INTEGER,
ADD COLUMN     "baseCleanRetail" INTEGER,
ADD COLUMN     "baseCleanTradeIn" INTEGER,
ADD COLUMN     "baseLoanValue" INTEGER,
ADD COLUMN     "baseRoughTradeIn" INTEGER,
ADD COLUMN     "bodyType" TEXT,
ADD COLUMN     "curbWeight" INTEGER,
ADD COLUMN     "cylinders" INTEGER,
ADD COLUMN     "doors" INTEGER,
ADD COLUMN     "drivetrain" TEXT,
ADD COLUMN     "engine" TEXT,
ADD COLUMN     "fuelType" TEXT,
ADD COLUMN     "liters" TEXT,
ADD COLUMN     "maxMileageAdj" INTEGER,
ADD COLUMN     "mileageClass" TEXT,
ADD COLUMN     "minAdjAverageTrade" INTEGER,
ADD COLUMN     "minAdjCleanTrade" INTEGER,
ADD COLUMN     "minAdjLoan" INTEGER,
ADD COLUMN     "minAdjRetail" INTEGER,
ADD COLUMN     "minAdjRetailForLoan" INTEGER,
ADD COLUMN     "minAdjRoughTrade" INTEGER,
ADD COLUMN     "minMileageAdj" INTEGER,
ADD COLUMN     "modelNumber" TEXT,
ADD COLUMN     "requestId" TEXT,
ADD COLUMN     "rollupVehicleId" TEXT,
ADD COLUMN     "transmission" TEXT,
ADD COLUMN     "trim2" TEXT,
ADD COLUMN     "ucgSubsegment" TEXT,
ADD COLUMN     "ucgVehicleId" TEXT,
ADD COLUMN     "vehicleType" TEXT,
ADD COLUMN     "vid" TEXT,
ADD COLUMN     "vinOptionsLoan" INTEGER,
ADD COLUMN     "vinOptionsRetail" INTEGER,
ADD COLUMN     "vinOptionsTradeIn" INTEGER;

-- CreateIndex
CREATE INDEX "Bookout_ucgVehicleId_idx" ON "Bookout"("ucgVehicleId");
